version: '3'
services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: cu-sportgo-booking
    restart: unless-stopped
    env_file:
      - .env 
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
  rabbitmq:
    image: rabbitmq:3.9.26-management-alpine
    container_name: cu-sportgo-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
volumes:
  postgres:
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local